<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MasterVendor;
use Illuminate\Support\Facades\DB;

class MasterVendorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Truncate existing data
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        MasterVendor::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $vendors = [
            [
                'kode_vendor' => 'BRG-001',
                'nama_vendor' => 'PT Berkah Jaya Bearing',
                'alamat_vendor' => 'Jl. Raya Industri No. 45, Jakarta Timur',
                'kota' => 'Jakarta',
                'provinsi' => 'DKI Jakarta',
                'kode_pos' => '13510',
                'telepon' => '021-8765-4321',
                'email' => 'info@berkahjayabearing.co.id',
                'person_in_charge' => 'Budi Santoso',
                'kebijakan_retur' => 'keduanya',
                'deskripsi' => 'Supplier bearing dan komponen mesin berkualitas tinggi',
                'is_active' => true,
            ],
            [
                'kode_vendor' => 'SKF-002',
                'nama_vendor' => 'CV Sumber Karya Fastener',
                'alamat_vendor' => 'Jl. Gatot Subroto No. 123, Bandung',
                'kota' => 'Bandung',
                'provinsi' => 'Jawa Barat',
                'kode_pos' => '40264',
                'telepon' => '022-7654-3210',
                'email' => 'sales@skfastener.com',
                'person_in_charge' => 'Ahmad Fauzi',
                'kebijakan_retur' => 'retur_fisik',
                'deskripsi' => 'Distributor fastener dan hardware industrial',
                'is_active' => true,
            ],
            [
                'kode_vendor' => 'MPL-003',
                'nama_vendor' => 'UD Mitra Plastik Lestari',
                'alamat_vendor' => 'Jl. Siliwangi No. 88, Bandung',
                'kota' => 'Bandung',
                'provinsi' => 'Jawa Barat',
                'kode_pos' => '40115',
                'telepon' => '022-8765-1234',
                'email' => 'contact@mitraplastik.co.id',
                'person_in_charge' => 'Siti Nurhaliza',
                'kebijakan_retur' => 'debit_note',
                'deskripsi' => 'Produsen komponen plastik injection molding',
                'is_active' => true,
            ],
            [
                'kode_vendor' => 'TMS-004',
                'nama_vendor' => 'PT Teknik Mesin Sejahtera',
                'alamat_vendor' => 'Kawasan Industri Jababeka Blok J No. 15',
                'kota' => 'Cikarang',
                'provinsi' => 'Jawa Barat',
                'kode_pos' => '17530',
                'telepon' => '021-8934-5678',
                'email' => 'info@teknikmesin.com',
                'person_in_charge' => 'Hendro Gunawan',
                'kebijakan_retur' => 'keduanya',
                'deskripsi' => 'Workshop machining parts dan komponen presisi',
                'is_active' => true,
            ],
            [
                'kode_vendor' => 'EKA-005',
                'nama_vendor' => 'CV Elektronik Abadi',
                'alamat_vendor' => 'Jl. Veteran No. 67, Surabaya',
                'kota' => 'Surabaya',
                'provinsi' => 'Jawa Timur',
                'kode_pos' => '60271',
                'telepon' => '031-5678-9012',
                'email' => 'elektronikabadi@gmail.com',
                'person_in_charge' => 'Rudi Hermawan',
                'kebijakan_retur' => 'retur_fisik',
                'deskripsi' => 'Supplier komponen elektronik dan PCB',
                'is_active' => true,
            ],
            [
                'kode_vendor' => 'KRS-006',
                'nama_vendor' => 'PT Karet Rubber Sentosa',
                'alamat_vendor' => 'Jl. Industri Raya No. 234, Jakarta Utara',
                'kota' => 'Jakarta',
                'provinsi' => 'DKI Jakarta',
                'kode_pos' => '14350',
                'telepon' => '021-6543-2109',
                'email' => 'sales@karetsentosa.co.id',
                'person_in_charge' => 'Dewi Kusuma',
                'kebijakan_retur' => 'debit_note',
                'deskripsi' => 'Produsen rubber seal dan gasket',
                'is_active' => true,
            ],
            [
                'kode_vendor' => 'LGM-007',
                'nama_vendor' => 'UD Logam Metal Perkasa',
                'alamat_vendor' => 'Jl. Pahlawan No. 156, Surabaya',
                'kota' => 'Surabaya',
                'provinsi' => 'Jawa Timur',
                'kode_pos' => '60174',
                'telepon' => '031-7654-3210',
                'email' => 'logamperkasa@yahoo.com',
                'person_in_charge' => 'Agus Salim',
                'kebijakan_retur' => 'keduanya',
                'deskripsi' => 'Distributor metal sheet dan plate',
                'is_active' => true,
            ],
            [
                'kode_vendor' => 'CHM-008',
                'nama_vendor' => 'CV Chemical Industries',
                'alamat_vendor' => 'Jl. Raya Bogor KM 45, Cibinong',
                'kota' => 'Bogor',
                'provinsi' => 'Jawa Barat',
                'kode_pos' => '16914',
                'telepon' => '021-8765-4320',
                'email' => 'chemical.ind@outlook.com',
                'person_in_charge' => 'Bambang Priyono',
                'kebijakan_retur' => 'debit_note',
                'deskripsi' => 'Supplier chemical dan adhesive industrial',
                'is_active' => false,
            ],
            [
                'kode_vendor' => 'PKG-009',
                'nama_vendor' => 'PT Packaging Solutions',
                'alamat_vendor' => 'Jl. MT Haryono No. 78, Jakarta Selatan',
                'kota' => 'Jakarta',
                'provinsi' => 'DKI Jakarta',
                'kode_pos' => '12810',
                'telepon' => '021-7890-1234',
                'email' => 'info@packagingsolutions.id',
                'person_in_charge' => 'Linda Wijaya',
                'kebijakan_retur' => 'retur_fisik',
                'deskripsi' => 'Produsen packaging dan material kemasan',
                'is_active' => true,
            ],
            [
                'kode_vendor' => 'TXT-010',
                'nama_vendor' => 'CV Tekstil Mandiri',
                'alamat_vendor' => 'Jl. Dago No. 234, Bandung',
                'kota' => 'Bandung',
                'provinsi' => 'Jawa Barat',
                'kode_pos' => '40135',
                'telepon' => '022-2345-6789',
                'email' => 'tekstilmandiri@gmail.com',
                'person_in_charge' => 'Yuni Astuti',
                'kebijakan_retur' => 'keduanya',
                'deskripsi' => 'Supplier textile dan fabric industrial',
                'is_active' => true,
            ],
            [
                'kode_vendor' => 'HYD-011',
                'nama_vendor' => 'PT Hydraulic Nusantara',
                'alamat_vendor' => 'Jl. Sudirman No. 567, Jakarta Pusat',
                'kota' => 'Jakarta',
                'provinsi' => 'DKI Jakarta',
                'kode_pos' => '10220',
                'telepon' => '021-5678-9012',
                'email' => 'hydraulic@nusantara.co.id',
                'person_in_charge' => 'Eko Prasetyo',
                'kebijakan_retur' => 'retur_fisik',
                'deskripsi' => 'Distributor komponen hydraulic sistem',
                'is_active' => true,
            ],
            [
                'kode_vendor' => 'PNM-012',
                'nama_vendor' => 'UD Pneumatic Makmur',
                'alamat_vendor' => 'Jl. Ahmad Yani No. 89, Surabaya',
                'kota' => 'Surabaya',
                'provinsi' => 'Jawa Timur',
                'kode_pos' => '60235',
                'telepon' => '031-8901-2345',
                'email' => 'pneumaticmakmur@hotmail.com',
                'person_in_charge' => 'Hadi Wijaya',
                'kebijakan_retur' => 'keduanya',
                'deskripsi' => 'Supplier pneumatic equipment dan spare part',
                'is_active' => true,
            ],
            [
                'kode_vendor' => 'ELC-013',
                'nama_vendor' => 'CV Elektrik Cahaya',
                'alamat_vendor' => 'Jl. Gajah Mada No. 123, Semarang',
                'kota' => 'Semarang',
                'provinsi' => 'Jawa Tengah',
                'kode_pos' => '50134',
                'telepon' => '024-3456-7890',
                'email' => 'elektrikalcahaya@gmail.com',
                'person_in_charge' => 'Sri Mulyani',
                'kebijakan_retur' => 'debit_note',
                'deskripsi' => 'Distributor electrical equipment',
                'is_active' => false,
            ],
            [
                'kode_vendor' => 'STL-014',
                'nama_vendor' => 'PT Steel Prima',
                'alamat_vendor' => 'Jl. Raya Cikarang No. 456, Cikarang',
                'kota' => 'Bekasi',
                'provinsi' => 'Jawa Barat',
                'kode_pos' => '17550',
                'telepon' => '021-8967-5432',
                'email' => 'steelprima@steelprima.com',
                'person_in_charge' => 'Joko Widodo',
                'kebijakan_retur' => 'keduanya',
                'deskripsi' => 'Produsen steel material dan konstruksi',
                'is_active' => true,
            ],
            [
                'kode_vendor' => 'ALM-015',
                'nama_vendor' => 'CV Aluminium Jaya',
                'alamat_vendor' => 'Jl. Pemuda No. 345, Bandung',
                'kota' => 'Bandung',
                'provinsi' => 'Jawa Barat',
                'kode_pos' => '40181',
                'telepon' => '022-4567-8901',
                'email' => 'aluminiumjaya@outlook.com',
                'person_in_charge' => 'Fitri Handayani',
                'kebijakan_retur' => 'retur_fisik',
                'deskripsi' => 'Supplier aluminium profile dan accessories',
                'is_active' => true,
            ],
            [
                'kode_vendor' => 'SFT-016',
                'nama_vendor' => 'PT Safety Equipment',
                'alamat_vendor' => 'Jl. Thamrin No. 678, Jakarta Pusat',
                'kota' => 'Jakarta',
                'provinsi' => 'DKI Jakarta',
                'kode_pos' => '10340',
                'telepon' => '021-3210-9876',
                'email' => 'safety@equipment.co.id',
                'person_in_charge' => 'Rina Susanti',
                'kebijakan_retur' => 'debit_note',
                'deskripsi' => 'Distributor safety equipment dan PPE',
                'is_active' => true,
            ],
            [
                'kode_vendor' => 'TLS-017',
                'nama_vendor' => 'UD Tools Hardware',
                'alamat_vendor' => 'Jl. Basuki Rahmat No. 234, Surabaya',
                'kota' => 'Surabaya',
                'provinsi' => 'Jawa Timur',
                'kode_pos' => '60271',
                'telepon' => '031-6789-0123',
                'email' => 'toolshardware@gmail.com',
                'person_in_charge' => 'Dedi Supriadi',
                'kebijakan_retur' => 'keduanya',
                'deskripsi' => 'Supplier hand tools dan perkakas',
                'is_active' => true,
            ],
            [
                'kode_vendor' => 'PSN-018',
                'nama_vendor' => 'PT Precision Engineering',
                'alamat_vendor' => 'Kawasan Industri MM2100, Cibitung',
                'kota' => 'Bekasi',
                'provinsi' => 'Jawa Barat',
                'kode_pos' => '17520',
                'telepon' => '021-8901-2346',
                'email' => 'precision@engineering.id',
                'person_in_charge' => 'Tony Gunawan',
                'kebijakan_retur' => 'retur_fisik',
                'deskripsi' => 'Workshop precision parts dan CNC machining',
                'is_active' => true,
            ],
            [
                'kode_vendor' => 'INS-019',
                'nama_vendor' => 'PT Insulasi Thermal',
                'alamat_vendor' => 'Jl. Raya Serpong No. 567, Tangerang',
                'kota' => 'Tangerang',
                'provinsi' => 'Banten',
                'kode_pos' => '15310',
                'telepon' => '021-5432-1098',
                'email' => 'insulasi@thermal.co.id',
                'person_in_charge' => 'Maya Sari',
                'kebijakan_retur' => 'debit_note',
                'deskripsi' => 'Supplier insulation material thermal',
                'is_active' => true,
            ],
            [
                'kode_vendor' => 'SPR-020',
                'nama_vendor' => 'CV Spring Components',
                'alamat_vendor' => 'Jl. Cikini Raya No. 123, Jakarta Pusat',
                'kota' => 'Jakarta',
                'provinsi' => 'DKI Jakarta',
                'kode_pos' => '10330',
                'telepon' => '021-3145-6789',
                'email' => 'springcomponents@yahoo.com',
                'person_in_charge' => 'Wawan Setiawan',
                'kebijakan_retur' => 'keduanya',
                'deskripsi' => 'Produsen spring dan coil komponen',
                'is_active' => true,
            ],
        ];

        foreach ($vendors as $vendor) {
            MasterVendor::create($vendor);
        }

        $this->command->info('✅ 20 Master Vendor data berhasil ditambahkan!');
    }
}
